### ISSUE TITLE
Update README to reference that API Key is Client ID

### ISSUE THREAD

**Issue by brenthosie** [Adobe-Marketing-Cloud/reactor-uploader#27]
When trying to run the uploader, I received this error:

```
Error retrieving access token. invalid client_id parameter
```

`client_id` is not referenced in the docs, but the Adobe console references that the Api Key is the Client ID.

Could we please update the error or README so this is more clear?

**Comment by frunkad** [comment]
Can I take this up?

**Comment by Aaronius** [comment]
@frunkad Please do!

**Comment by frunkad** [comment]
Couldn't access the Adobe Console for Adobe Experience Platform API Key as it requires me to register as an organization. 

Also, apparently from line 103 of `getIntegrationAccessToken,js`, both clientId and apiKey are the same thing, so I have submitted a PR that updates README file to indicate both are one and same thing. There are further things that could be done (mentioned in the PR) but need a nod from your side.

**Comment by Aaronius** [comment]
I've merged @frunkad's PR, which helps clarify the terminology everywhere except the actual `Error retrieving access token. invalid client_id parameter` message. That message comes from the server and I'm hesitant to do string matching on the message they provide.
