### ISSUE TITLE
Support Proxy Servers

### ISSUE THREAD

**Issue by brenthosie** [Adobe-Marketing-Cloud/reactor-uploader#46]
### Expected Behaviour

`reactor-uploader` should expose a way to pass options for sending calls through a proxy server. Auth credentials should not required but should be available.

### Actual Behaviour

proxy calls are not supported

### Related Issues

Relates to the comments that emerged within #28 and https://github.com/adobe/jwt-auth/pull/51

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Story

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Story

**Comment by alcazes** [comment]
Any update on this ?

**Comment by brenthosie** [comment]
I'm trying to get an answer for you. I'm noticing that [this still hasn't been](https://github.com/adobe/jwt-auth/pull/51) merged, which is a prerequisite for us to even add support here.

Trying to talk with someone on that team to see what the holdup is. Do you currently have a workaround in place?

**Comment by alcazes** [comment]
We have an old forked version that my colleague customised so it can work in our company’s intranet. However it has not been updated in a while. Would rather prefer to use the official one.

**Comment by brenthosie** [comment]
@alcazes We've been having a lot of internal discussions and we have someone that can merge PRs on `jwt-auth`. I reached out to the original author on Friday to see if he had interest in managing his PR and responding to new comments. Would you be interested in forking and driving the PR on `jwt-auth` and then we can talk about moving forward on the change necessary for validator?

**Comment by brenthosie** [comment]
@alcazes Is this still a requirement for you? We've got the rights to change `jwt-auth` now. Perhaps we could schedule a call to go over your use case?

**Comment by brenthosie** [comment]
Reference https://github.com/adobe/jwt-auth/issues/50 & https://github.com/adobe/jwt-auth/pull/51

**Comment by alcazes** [comment]
Yes we still cannot use the Adobe launch uploader and we still have to use our customized one. I would rather use the Adobe one as our version must be way behind.

Unfortunately I will not be able to do the changes.

**Comment by brenthosie** [comment]
@alcazes I'm not asking you to do the changes, I'd like to meet and discuss your use-case to ensure we get the correct changes in for the official Adobe uploader. Will you reach out with your availability for next week to brenthosie [at] gmail dot com ?

**Comment by brenthosie** [comment]
@alcazes If the direction we parted with isn't meeting your needs, let's open a new issue with new specific asks. Thank you.
