### ISSUE TITLE
Error retrieving your Access Token: This is likely an error within jwt-auth or the IMS token exchange service

### ISSUE THREAD

**Issue by JurajLigo** [Adobe-Marketing-Cloud/reactor-uploader#56]
I am trying to call npx @adobe/reactor-uploader with parameters, but I am getting error
Error retrieving your Access Token: This is likely an error within jwt-auth or the IMS token exchange service
Error Message: Request failed while swapping the jwt token. request to https://ims-na1.adobelogin.com/ims/exchange/jwt/ failed, reason: self signed certificate in certificate chain
Error Code: request_failed

Do I need also send jwt or am I missing some point?

**Comment by brenthosie** [comment]
Hello @JurajLigo 

To better troubleshoot, can you try running uploader with the `--verbose` flag? If you want to chat in slack instead, we have developer help at this slack server: https://docs.google.com/forms/d/e/1FAIpQLScq1m63YkDrRpvPLhzUqtfoleWiDDTTXZsSivIXRfFdlSMzpQ/viewform

I have an account there and can speak with you quicker.

**Comment by JurajLigo** [comment]
Hello, 
Sorry I don't have account in Slack, so I would prefer writing here.  I tried it with --verbose flag. Here is output:
Authenticating with metascope ent_reactor_sdk
----------
--verbose output:
/Users/s204a/.npm/_npx/469a399eea44b569/node_modules/@adobe/jwt-auth/index.js:23
  const error = new Error(
                ^

Error: Request failed while swapping the jwt token. request to https://ims-na1.adobelogin.com/ims/exchange/jwt/ failed, reason: self signed certificate in certificate chain
    at throwRequestFailedError (/Users/s204a/.npm/_npx/469a399eea44b569/node_modules/@adobe/jwt-auth/index.js:23:17)
    at /Users/s204a/.npm/_npx/469a399eea44b569/node_modules/@adobe/jwt-auth/index.js:108:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/s204a/.npm/_npx/469a399eea44b569/node_modules/@adobe/reactor-uploader/bin/getIntegrationAccessToken.js:102:24)
    at async /Users/s204a/.npm/_npx/469a399eea44b569/node_modules/@adobe/reactor-uploader/bin/index.js:73:36 {
  code: 'request_failed'
}

**Comment by brenthosie** [comment]
This part looks pretty suspect to me: `reason: self signed certificate in certificate chain`

is it possible you've got a proxy server turned on and you're redirecting traffic away from Adobe's services?

**Comment by brenthosie** [comment]
re-open if you're still experiencing the problem with more clarification.
