### ISSUE TITLE
OAuth Server-to-Server credential support

### ISSUE THREAD

**Issue by mems** [Adobe-Marketing-Cloud/reactor-uploader#63]
Currently Service Account (JWT) using private key is the only credential type supported by reactor-uploader.

But [the Service Account (JWT) credentials have been deprecated in favor of the new OAuth Server-to-Server credentials](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration/).

See also https://github.com/adobe/reactor-releaser/issues/28

**Comment by ghost** [comment]
Any update on this?

**Comment by brenthosie** [comment]
@vaibhavmo PR incoming soon

**Comment by brenthosie** [comment]
See `v5.0.0-beta.12` as of this comment.

**Comment by h-singhal** [comment]
Any update on this?
