### ISSUE TITLE
Beta Version of Package Pushed to NPM without documentation

### ISSUE THREAD

**Issue by adam-hiatt** [Adobe-Marketing-Cloud/reactor-uploader#67]
### Expected Behaviour
OAUTH Flow documented or not pushed to production without notification. Additionally, if there is an error during execution the error cause should be printed to the console and not the generic runtime error. When introducing breaking changes this should be clearly communicated in the documentation. 

### Actual Behaviour
When I attempted to upload a new version of my tags extension it prompted me for my client ID and after entering it the uploader just stopped with a message of `TypeError: func.apply is not a function`. I did not run into this the last time I used the package so I looked into the releases, and npm publish date for the package and noticed that a beta version was pushed to NPM that disables the JWT flow and enables OAUTH. I believe this may have been unintentional as it was not documented anywhere and the version name is beta, but it is the default version that is downloaded when using NPM. Switching back to version 5.1.1 resolves this error. 

### Reproduce Scenario (including but not limited to)
Follow the instructions in the README and the error is produced. 

#### Platform and Version
6.0.0-beta.12

#### Logs taken while reproducing problem
![image](https://github.com/adobe/reactor-uploader/assets/100222251/e10aaf3b-0ea6-41b2-b943-7663c243782a)

**Comment by brenthosie** [comment]
This was completely unintentional and should be resolved now. Can you try running the uploader again? The `beta` version should only be on our `@adobe/reactor-uplaoder@next` tag.

**Comment by adam-hiatt** [comment]
> This was completely unintentional and should be resolved now. Can you try running the uploader again? The `beta` version should only be on our `@adobe/reactor-uplaoder@next` tag.

Thanks for the quick response! And yes, just ran it and it is working as expected now. Thank you!

**Comment by johndavidsimmons** [comment]
@brenthosie I'm getting this issue on `npx @adobe/reactor-uploader@next` as well as the `auth-token-next-2` and `auth-token-next-3` branches...
<img width="870" alt="Screenshot 2024-08-29 at 2 11 10 PM" src="https://github.com/user-attachments/assets/89f148bf-a5ff-49ae-a356-6bb82120fe2e">
