### ISSUE TITLE
Error : OAuth Server-to-Server credential support

### ISSUE THREAD

**Issue by h-singhal** [Adobe-Marketing-Cloud/reactor-uploader#70]
When we are trying to use v6.0.0-beta.11 or v6.0.0-beta.12 or v6.0.0-beta.13...
we are getting below Error :

![image](https://github.com/user-attachments/assets/8153813d-ec27-4c91-b9fd-068668f000f4)

Any update to support the oauth-server-to-server credential Type

**Comment by adam-hiatt** [comment]
Following this

**Comment by jeffreywalter** [comment]
This issue has come up in a few different places. We placed it near the top of the backlog and will be taking a look at this soon. We will update this issue when it's fixed!

**Comment by Mae-Adf** [comment]
Currently it is not possible to add JWT credentials to the Experience Platform API and the beta versions of the uploader still only return the same error of the original poster. Is there a way to use the API with the OAuth S2S credentials at all?

**Comment by johndavidsimmons** [comment]
Is it currently possible to use reactor-uploader with oauth s2s credentials on any branch?

**Comment by brenthosie** [comment]
Thank you everyone for your patience. Does the issue resolve for you using `@adobe/reactor-uploader@6.0.0-beta.15` (`@adobe/reactor-uploader@next`)?

**Comment by Mae-Adf** [comment]
> Thank you everyone for your patience. Does the issue resolve for you using `@adobe/reactor-uploader@6.0.0-beta.15` (`@adobe/reactor-uploader@next`)?

Yes, after redownloading @adobe/reactor-uploader@next I was able to upload a package without any issues.

**Comment by brenthosie** [comment]
closed by #66
