### ISSUE TITLE
Verbose mode should not print access token

### ISSUE THREAD

**Issue by jeffreywalter** [Adobe-Marketing-Cloud/reactor-uploader#8]
Although super useful, we have a tendency to copy-paste the entire verbose output into a group chat or forum.
This is probably not a great idea since it includes the access token in the output.
The access token can be used to access the API arbitrarily and should be treated a bit more securely.
I still like the access token to be able to troubleshoot tho. Can we add a -vv or env variable switch or something?

**Comment by dompuiu** [comment]
Access token option will no longer be supported: https://github.com/Adobe-Marketing-Cloud/reactor-uploader/pull/12.

**Comment by Aaronius** [comment]
I don't think https://github.com/Adobe-Marketing-Cloud/reactor-uploader/pull/12 actually addresses this issue. An access token will still show up in verbose mode, it will just be the one from the JWT swap rather than a user-provided one. They're both sensitive.

**Comment by brenthosie** [comment]
Addressed by #43
